In [1]:
# Install spaCy

!pip install -U spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.13/dist-packages (3.8.16)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.13/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.5.4)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (0.27.3)
Requirement already satisfied: click<9.0.0,>=8.2.1 in /usr/local/lib/python3.13/dist-packages (from spacy) (8.5.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.14.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from spacy) (80.10.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (26.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.50.1)
Requirement already satisfied: typing-extensions>=4.16.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.10.19)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.5)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.26.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.4)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->spacy) (3.0.4)

In [2]:
# Import Libraries

import spacy
from spacy import displacy #module for visualizing linguistic dependencies
from collections import Counter
import pandas as pd #commonly used for data manipulation and analysis
pd.options.display.max_rows = 600
pd.options.display.max_colwidth = 400

In [4]:
# Download Language Model

!python -m spacy download en_core_web_sm #model is necessary for processing English text and performing tasks like part-of-speech tagging and dependency parsing

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 14.5 MB/s  0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [5]:
# Load Language Model

nlp = spacy.load('en_core_web_sm')

In [6]:
# Create a Processed spaCy Document
# Whenever we use spaCy, our first step will be to create a processed spaCy document with the loaded NLP model nlp(). Most of the heavy NLP lifting is done in this line of code.
# To test out spaCy’s part-of-speech tagging, we’ll begin by processing a sample sentence

sample = """She “has thrown her magical spell around the most abstract of Sciences."""

document = nlp(sample)

In [10]:
# To quickly see spaCy’s POS tagging in action, we can use the spaCy module displacy on our sample document with the style= parameter set to “dep” (short for dependency parsing):

#Set some display options for the visualizer
options = {"compact": True, "distance": 90, "color": "yellow", "bg": "black", "font": "Gill Sans"}

displacy.render(document, style="dep", options=options)

In [11]:
# spaCy has correctly identified that “spell” and “force” are nouns in our sample sentence:

for token in document:
    if token.pos_ == "NOUN":
        print(token, token.pos_)

spell NOUN
abstract NOUN

In [12]:
# But if we look at the same words in a different context

document = nlp("You shouldn't force someone to learn how to spell Babbage. They just need practice. You can't abstract it.")

In [13]:
for token in document:
    if token.pos_ == "VERB":
        print(token, token.pos_)

force VERB
learn VERB
spell VERB
need VERB
abstract VERB

## Get Part-Of-Speech Tags

In [14]:
# To get part of speech tags for every word in a document, we have to iterate through all the tokens in the document and pull out the .pos_ attribute for each token. We can get even finer-grained dependency information with the attribute .dep_.

for token in document:
    print(token.text, token.pos_, token.dep_)

You PRON nsubj
should AUX aux
n't PART neg
force VERB ROOT
someone PRON dobj
to PART aux
learn VERB xcomp
how SCONJ advmod
to PART aux
spell VERB xcomp
Babbage PROPN dobj
. PUNCT punct
They PRON nsubj
just ADV advmod
need VERB ROOT
practice NOUN dobj
. PUNCT punct
You PRON nsubj
ca AUX aux
n't PART neg
abstract VERB ROOT
it PRON dobj
. PUNCT punct

In [15]:
filepath = "Dracula_Bram-Stoker.txt"
document = nlp(open(filepath, encoding="utf-8").read())

In [16]:
# Get Adjectives

adjs = []
for token in document:
    if token.pos_ == 'ADJ':
        adjs.append(token.text)

adjs

['most',
 'other',
 '*',
 'manifest',
 'needless',
 'later',
 'simple',
 'past',
 'contemporary',
 '1st',
 'next',
 'wonderful',
 'little',
 'correct',
 'possible',
 'western',
 'splendid',
 'noble',
 'Turkish',
 'good',
 'red',
 'good',
 'thirsty',
 'national',
 'able',
 'useful',
 'able',
 'extreme',
 'Carpathian',
 'wildest',
 'able',
 'exact',
 'own',
 'post',
 'distinct',
 'latter',
 'eleventh',
 'imaginative',
 'interesting',
 'comfortable',
 'thirsty',
 'continuous',
 'more',
 'mamaliga',
 'excellent',
 'little',
 'more',
 'further',
 'more',
 'unpunctual',
 'full',
 'little',
 'steep',
 'such',
 'old',
 'wide',
 'stony',
 'subject',
 'great',
 'strong',
 'outside',
 'clear',
 'short',
 'round',
 'picturesque',
 'pretty',
 'clumsy',
 'full',
 'white',
 'other',
 'most',
 'big',
 'strangest',
 'barbarian',
 'big',
 'great',
 'baggy',
 'dirty',
 'white',
 'white',
 'enormous',
 'heavy',
 'wide',
 'high',
 'long',
 'black',
 'heavy',
 'black',
 'picturesque',
 'old',
 'Oriental',
 'harmless',
 'natural',
 'dark',
 'interesting',
 'old',
 'stormy',
 'great',
 'terrible',
 'separate',
 'very',
 'seventeenth',
 'proper',
 'great',
 'old',
 'elderly',
 'usual',
 'white',
 'long',
 'double',
 'coloured',
 'tight',
 'modesty',
 'close',
 'elderly',
 'white',
 'happy',
 'beautiful',
 'best',
 'reticent',
 'true',
 'least',
 'old',
 'other',
 'frightened',
 'mysterious',
 'old',
 'hysterical',
 'young',
 'excited',
 'German',
 'other',
 'able',
 'many',
 'important',
 'fourth',
 'evil',
 'full',
 'such',
 'evident',
 'least',
 'ridiculous',
 'comfortable',
 'imperative',
 'such',
 'idolatrous',
 'ungracious',
 'old',
 'old',
 'many',
 'ghostly',
 'easy',
 'usual',
 'high',
 'distant',
 'jagged',
 'big',
 'little',
 'mixed',
 'sleepy',
 'many',
 'odd',
 'red',
 'simple',
 'disagreeable',
 'most',
 'many',
 'polyglot',
 'same',
 'Slovak',
 'other',
 'considerable',
 'first',
 'evil',
 'pleasant',
 'unknown',
 'unknown',
 'sorrowful',
 'sympathetic',
 'last',
 'picturesque',
 'wide',
 'rich',
 'green',
 'wide',
 'whole',
 'big',
 'small',
 'abreast',
 'ghostly',
 'able',
 'green',
 'full',
 'steep',
 'blank',
 'gable',
 'bewildering',
 'green',
 'fallen',
 'green',
 'pine',
 'feverish',
 'bent',
 'excellent',
 'different',
 'general',
 'old',
 'good',
 'old',
 'foreign',
 'green',
 'mighty',
 'lofty',
 'full',
 'glorious',
 'beautiful',
 'deep',
 'purple',
 'green',
 'brown',
 'endless',
 'jagged',
 'pointed',
 'snowy',
 'mighty',
 'white',
 'lofty',
 'serpentine',
 'right',
 'endless',
 'lower',
 'snowy',
 'delicate',
 'cool',
 'picturesque',
 'prevalent',
 'many',
 'outer',
 'many',
 'new',
 'beautiful',
 'delicate',
 'ordinary',
 'long',
 'like',
 'sure',
 'white',
 'latter',
 'long',
 'cold',
 'dark',
 'dark',
 'great',
 'greyness',
 'weird',
 'solemn',
 'grim',
 'strange',
 'like',
 'steep',
 'fierce',
 'grim',
 'enough',
 'such',
 'only',
 'dark',
 'other',
 'further',
 'long',
 'wild',
 'further',
 'grey',
 'greater',
 'crazy',
 'great',
 'stormy',
 'level',
 'several',
 'odd',
 'varied',
 'simple',
 'good',
 'kindly',
 'strange',
 'evil',
 'evident',
 'exciting',
 'slightest',
 'little',
 'eastern',
 'dark',
 'rolling',
 'heavy',
 'oppressive',
 'thunderous',
 'dark',
 'only',
 'own',
 'white',
 'sandy',
 'white',
 'own',
 'best',
 'low',
 'less',
 'German',
 'worse',
 'next',
 'better',
 'next',
 'universal',
 'black',
 'splendid',
 'tall',
 'long',
 'brown',
 'great',
 'black',
 'bright',
 'red',
 'early',
 'stranger',
 'much',
 'swift',
 'red',
 'white',
 'dead',
 'strange',
 'same',
 'close',
 'prodigious',
 'late',
 'strange',
 'lonely',
 'excellent',
 'mein',
 'same',
 'little',
 'little',
 'frightened',
 'unknown',
 'hard',
 'complete',
 'straight',
 'same',
 'curious',
 'few',
 'general',
 'recent',
 'sick',
 'long',
 'wild',
 'first',
 'rear',
 'sudden',
 'louder',
 'sharper',
 'same',
 'minded',
 'great',
 'few',
 'own',
 'quiet',
 'able',
 'extraordinary',
 'manageable',
 'great',
 'far',
 'narrow',
 'great',
 'colder',
 'colder',
 'fine',
 'white',
 'keen',
 'nearer',
 'afraid',
 'least',
 'disturbed',
 'right',
 'faint',
 'blue',
 'same',
 'less',
 'asleep',
 'awful',
 'blue',
 'faint',
 'few',
 'strange',
 'optical',
 'flicker',
 'same',
 'momentary',
 'blue',
 'last',
 'worse',
 'black',
 'jagged',
 'white',
 'red',
 'long',
 'shaggy',
 'more',
 'terrible',
 'grim',
 'such',
 'true',
 'peculiar',
 'round',
 'painful',
 'only',
 'imperious',
 'long',
 'impalpable',
 'heavy',
 'strange',
 'uncanny',
 'dreadful',
 'afraid',
 'interminable',
 'complete',
 'rolling',
 'occasional',
 'quick',
 'main',
 'conscious',
 'vast',
 'tall',
 'black',
 'broken',
 'jagged',
 'moonlit',
 'asleep',
 'awake',
 'remarkable',
 'considerable',
 'several',
 'dark',
 'great',
 'round',
 'bigger',
 'able',
 'prodigious',
 'great',
 'old',
 'large',
 'massive',
 'dim',
 'dark',
 'dark',
 'likely',
 'endless',
 'grim',
 'customary',
 'successful',
 'blown',
 'awake',
 'horrible',
 'awake',
 'awake',
 'patient',
 'heavy',
 'great',
 'massive',
 'loud',
 'long',
 'great',
 'tall',
 'old',
 'clean',
 'shaven',
 'long',
 'white',
 'single',
 'antique',
 'long',
 'open',
 'old',
 'right',
 'excellent',
 'strange',
 'own',
 'cold',
 'dead',
 'akin',
 'same',
 'sure',
 'courtly',
 'chill',
 'late',
 'available',
 'great',
 'great',
 'heavy',
 'mighty',
 'great',
 'small',
 'octagonal',
 'single',
 'great',
 'top',
 'fresh',
 'hollow',
 'wide',
 'ready',
 'other',
 'courteous',
 'normal',
 'hasty',
 'other',
 'great',
 'graceful',
 'sealed',
 'charming',
 'least',
 'constant',
 'happy',
 'sufficient',
 'possible',
 'young',
 'full',
 'own',
 'faithful',
 'discreet',
 'silent',
 'ready',
 'excellent',
 'old',
 'many',
 'same',
 'marked',
 'strong',
 'strong',
 'high',
 'thin',
 'lofty',
 'domed',
 'massive',
 'bushy',
 'own',
 'heavy',
 'looking',
 'sharp',
 'white',
 'remarkable',
 'astonishing',
 'pale',
 'broad',
 'strong',
 'thin',
 'general',
 'extraordinary',
 'white',
 'fine',
 'coarse',
 'broad',
 'squat',
 'Strange',
 'long',
 'fine',
 'sharp',
 'rank',
 'horrible',
 'grim',
 'more',
 'protuberant',
 'own',
 'silent',
 'first',
 'dim',
 'strange',
 'many',
 'strange',
 'tired',
 'ready',
 'courteous',
 'octagonal',
 'strange',
 'confess',
 'own',
 'dear',
 'early',
 'last',
 'own',
 'cold',
 'hot',
 'absent',
 'hearty',
 'odd',
 'extraordinary',
 'round',
 'immense',
 'costliest',
 'beautiful',
 'fabulous',
 'old',
 'excellent',
 'little',
 'shaving',
 'great',
 'vast',
 'English',
 'whole',
 'full',
 'English',
 'recent',
 'varied',
 'political',
 'English',
 'such',
 'Blue',
 'hearty',
 'good',
 'glad',
 'sure',
 'much',
 'good',
 'many',
 'many',
 'great',
 'crowded',
 'mighty',
 'flattering',
 'little',
 'True',
 'enough',
 'noble',
 'common',
 'strange',
 'content',
 'long',
 'least',
 'other',
 'alone',
 'new',
 'English',
 'smallest',
 'sorry',
 'long',
 'many',
 'important',
 'willing',
 'locked',
 'sure',
 'many',
 'strange',
 'strange',
 'much',
 'evident',
 'many',
 'bolder',
 'strange',
 'blue',
 'certain',
 'last',
 'evil',
 'unchecked',
 'blue',
 'last',
 'little',
 'old',
 'aged',
 'artificial',
 'triumphant',
 'little',
 'friendly',
 'undiscovered',
 'sure',
 'long',
 'sharp',
 'dear',
 'own',
 'able',
 'right',
 'more',
 'other',
 'last',
 'own',
 'next',
 'interested',
 'myriad',
 'more',
 'needful',
 'alone',
 'other',
 'necessary',
 'ready',
 'suitable',
 'dilapidated',
 'high',
 'ancient',
 'heavy',
 'large',
 'closed',
 'heavy',
 'old',
 'old',
 'sided',
 'cardinal',
 'solid',
 'many',
 'gloomy',
 'deep',
 'small',
 'clear',
 'fair',
 'sized',
 'large',
 'mediæval',
 'thick',
 'few',
 'close',
 'old',
 'various',
 'straggling',
 'great',
 'few',
 'close',
 'large',
 'private',
 'lunatic',
 'visible',
 'glad',
 'old',
 'big',
 'old',
 'new',
 'habitable',
 'few',
 'old',
 'Transylvanian',
 'common',
 'bright',
 'much',
 'young',
 'gay',
 'young',
 'weary',
 'attuned',
 'many',
 'cold',
 'alone',
 'malignant',
 'little',
 'certain',
 'little',
 'new',
 'other',
 'better',
 'Good',
 'ready',
 'next',
 'excellent',
 'ready',
 'previous',
 'last',
 'conceivable',
 'sleepy',
 'long',
 'preternatural',
 'clear',
 'remiss',
 'dear',
 'new',
 'interesting',
 'courtly',
 'own',
 'little',
 'warm',
 'glad',
 'first',
 'strange',
 'uneasy',
 'safe',
 'strange',
 'only',
 'prosaic',
 'few',
 'Good',
 'whole',
 'close',
 'whole',
 'startling',
 'many',
 'strange',
 'vague',
 'near',
 'little',
 'half',
 'round',
 'instant',
 'dangerous',
 'wretched',
 'bauble',
 'heavy',
 'terrible',
 'annoying',
 'strange',
 'peculiar',
 'little',
 'magnificent',
 'very',
 'terrible',
 'green',
 'deep',
 'silver',
 'deep',
 'locked',
 'castle',
 'available',
 'veritable',
 'wild',
 'little',
 'other',
 'few',
 'mad',
 'much',
 'helpless',
 'best',
 'definite',
 'certain',
 'own',
 'only',
 'open',
 'own',
 'desperate',
 'latter',
 'great',
 'own',
 'odd',
 'menial',
 'terrible',
 'terrible',
 'wild',
 'good',
 'good',
 'odd',
 'idolatrous',
 'medium',
 'tangible',
 'careful',
 'long',
 'few',
 'present',
 'own',
 'fascinating',
 'whole',
 'excited',
 'great',
 'white',
 'main',
 'proud',
 'many',
 'brave',
 'European',
 'Ugric',
 'such',
 'fell',
 'warlike',
 'old',
 'great',
 'proud',
 'strange',
 'Hungarian',
 'Hungarian',
 'victorious',
 'more',
 'endless',
 'sleepless',
 'bloody',
 'warlike',
 'great',
 'own',
 'own',
 'own',
 'unworthy',
 'other',
 'later',
 'great',
 'alone',
 'bloody',
 'good',
 'free',
 'young',
 'warlike',
 'precious',
 'dishonourable',
 'great',
 'bare',
 'own',
 'Last',
 'legal',
 'certain',
 'certain',
 'useful',
 'more',
 'wise',
 'more',
 'certain',
 'practical',
 'local',
 'beautiful',
 'good',
 'strange',
 'local',
 'much',
 'more',
 'easy',
 'other',
 'local',
 'further',
 'such',
 'Good',
 'best',
 'wonderful',
 'much',
 'wonderful',
 'available',
 'first',
 'other',
 'young',
 'heavy',
 'other',
 'cold',
 'own',
 'smooth',
 'good',
 'young',
 'other',
 'well',
 'thinnest',
 'foreign',
 'quiet',
 'sharp',
 'red',
 'careful',
 'able',
 'formal',
 'quiet',
 'several',
 'own',
 'third',
 'fourth',
 'second',
 'fourth',
 'about',
 'much',
 'private',
 'dear',
 'young',
 'other',
 'old',
 'many',
 'bad',
 'like',
 'own',
 'safe',
 'careful',
 'gruesome',
 'only',
 'terrible',
 'unnatural',
 'horrible',
 'last',
 'freer',
 'little',
 'vast',
 'inaccessible',
 'narrow',
 'fresh',
 'nocturnal',
 'own',
 'full',
 'horrible',
 'terrible',
 'accursed',
 'beautiful',
 'soft',
 'yellow',
 'light',
 'soft',
 'distant',
 'mere',
 'own',
 'tall',
 'deep',
 'complete',
 'many',
 'many',
 'interested',
 'amused',
 'wonderful',
 'small',
 'very',
 'whole',
 'castle',
 'dreadful',
 'great',
 'weird',
 ...]

In [17]:
# we count the unique adjectives in this list with the Counter() module:

adjs_tally = Counter(adjs)

adjs_tally.most_common()

[('good', 202),
 ('other', 188),
 ('old', 188),
 ('more', 187),
 ('own', 184),
 ('great', 173),
 ('poor', 171),
 ('little', 162),
 ('much', 151),
 ('dear', 150),
 ('such', 133),
 ('same', 110),
 ('last', 108),
 ('white', 104),
 ('many', 100),
 ('terrible', 98),
 ('full', 97),
 ('long', 88),
 ('few', 86),
 ('strange', 85),
 ('first', 78),
 ('new', 74),
 ('ready', 70),
 ('whole', 66),
 ('open', 66),
 ('red', 65),
 ('sweet', 65),
 ('dead', 64),
 ('dark', 62),
 ('strong', 60),
 ('very', 60),
 ('true', 54),
 ('heavy', 53),
 ('young', 53),
 ('right', 49),
 ('able', 47),
 ('happy', 47),
 ('asleep', 47),
 ('big', 44),
 ('quick', 44),
 ('small', 43),
 ('sure', 43),
 ('best', 42),
 ('cold', 42),
 ('better', 42),
 ('wild', 41),
 ('free', 41),
 ('certain', 40),
 ('present', 40),
 ('afraid', 39),
 ('pale', 38),
 ('quiet', 37),
 ('silent', 36),
 ('alone', 36),
 ('high', 35),
 ('close', 35),
 ('glad', 35),
 ('round', 34),
 ('usual', 33),
 ('thin', 33),
 ('sad', 33),
 ('possible', 32),
 ('least', 32),
 ('bad', 32),
 ('beautiful', 31),
 ('low', 31),
 ('awful', 31),
 ('hard', 30),
 ('brave', 30),
 ('next', 29),
 ('deep', 29),
 ('Good', 29),
 ('mad', 29),
 ('anxious', 28),
 ('wonderful', 27),
 ('empty', 27),
 ('electronic', 27),
 ('late', 26),
 ('sudden', 25),
 ('horrible', 25),
 ('sharp', 25),
 ('necessary', 25),
 ('fair', 25),
 ('safe', 25),
 ('half', 25),
 ('Dead', 25),
 ('black', 24),
 ('grim', 24),
 ('only', 24),
 ('bright', 24),
 ('awake', 24),
 ('wide', 23),
 ('different', 23),
 ('fresh', 23),
 ('tired', 23),
 ('common', 23),
 ('noble', 21),
 ('short', 21),
 ('dreadful', 21),
 ('bitter', 21),
 ('odd', 20),
 ('enough', 20),
 ('less', 20),
 ('Poor', 20),
 ('weak', 20),
 ('satisfied', 20),
 ('most', 19),
 ('ill', 19),
 ('wrong', 19),
 ('evident', 18),
 ('worse', 18),
 ('fine', 18),
 ('real', 18),
 ('evil', 17),
 ('careful', 17),
 ('-', 17),
 ('earnest', 17),
 ('simple', 16),
 ('latter', 16),
 ('several', 16),
 ('second', 16),
 ('clever', 16),
 ('hypnotic', 16),
 ('easy', 15),
 ('sleepy', 15),
 ('fierce', 15),
 ('greater', 15),
 ('complete', 15),
 ('well', 15),
 ('sane', 15),
 ('sacred', 15),
 ('angry', 15),
 ('cheerful', 15),
 ('blind', 15),
 ('excellent', 14),
 ('like', 14),
 ('tall', 14),
 ('Last', 14),
 ('soft', 14),
 ('foul', 14),
 ('worth', 14),
 ('nice', 14),
 ('grave', 14),
 ('green', 13),
 ('general', 13),
 ('blue', 13),
 ('large', 13),
 ('fearful', 13),
 ('surprised', 13),
 ('alive', 13),
 ('past', 12),
 ('further', 12),
 ('clear', 12),
 ('important', 12),
 ('considerable', 12),
 ('faint', 12),
 ('various', 12),
 ('impossible', 12),
 ('nervous', 12),
 ('unhappy', 12),
 ('personal', 12),
 ('stern', 12),
 ('grateful', 12),
 ('useful', 11),
 ('unknown', 11),
 ('solemn', 11),
 ('early', 11),
 ('sick', 11),
 ('conscious', 11),
 ('broken', 11),
 ('sufficient', 11),
 ('hot', 11),
 ('thick', 11),
 ('dangerous', 11),
 ('precious', 11),
 ('wise', 11),
 ('calm', 11),
 ('lovely', 11),
 ('human', 11),
 ('violent', 11),
 ('selfish', 11),
 ('special', 11),
 ('rough', 11),
 ('kind', 11),
 ('™', 11),
 ('interesting', 10),
 ('mighty', 10),
 ('endless', 10),
 ('grey', 10),
 ('painful', 10),
 ('main', 10),
 ('loud', 10),
 ('broad', 10),
 ('willing', 10),
 ('uneasy', 10),
 ('desperate', 10),
 ('mere', 10),
 ('voluptuous', 10),
 ('serious', 10),
 ('physical', 10),
 ('stronger', 10),
 ('tiny', 10),
 ('particular', 10),
 ('exact', 9),
 ('comfortable', 9),
 ('steep', 9),
 ('natural', 9),
 ('double', 9),
 ('mysterious', 9),
 ('distant', 9),
 ('foreign', 9),
 ('lower', 9),
 ('lonely', 9),
 ('curious', 9),
 ('extraordinary', 9),
 ('narrow', 9),
 ('sorry', 9),
 ('previous', 9),
 ('near', 9),
 ('unconscious', 9),
 ('difficult', 9),
 ('holy', 9),
 ('active', 9),
 ('later', 8),
 ('excited', 8),
 ('ordinary', 8),
 ('far', 8),
 ('peculiar', 8),
 ('dim', 8),
 ('patient', 8),
 ('available', 8),
 ('faithful', 8),
 ('lunatic', 8),
 ('warm', 8),
 ('vague', 8),
 ('helpless', 8),
 ('local', 8),
 ('about', 8),
 ('former', 8),
 ('deadly', 8),
 ('due', 8),
 ('worst', 8),
 ('out:--', 8),
 ('similar', 8),
 ('resolute', 8),
 ('secret', 8),
 ('miserable', 8),
 ('funny', 8),
 ('absolute', 8),
 ('busy', 8),
 ('strait', 8),
 ('spiritual', 8),
 ('eager', 8),
 ('rare', 8),
 ('Un', 8),
 ('equal', 8),
 ('pretty', 7),
 ('tight', 7),
 ('frightened', 7),
 ('sharper', 7),
 ('successful', 7),
 ('single', 7),
 ('courteous', 7),
 ('English', 7),
 ('interested', 7),
 ('proud', 7),
 ('yellow', 7),
 ('gentle', 7),
 ('south', 7),
 ('More', 7),
 ('dearest', 7),
 ('regular', 7),
 ('accurate', 7),
 ('armed', 7),
 ('weaker', 7),
 ('rusty', 7),
 ('utmost', 7),
 ('mental', 7),
 ('ghastly', 7),
 ('dry', 7),
 ('stertorous', 7),
 ('needless', 6),
 ('correct', 6),
 ('cool', 6),
 ('recent', 6),
 ('hollow', 6),
 ('hearty', 6),
 ('private', 6),
 ('visible', 6),
 ('weary', 6),
 ('bare', 6),
 ('legal', 6),
 ('light', 6),
 ('dusty', 6),
 ('upset', 6),
 ('fatal', 6),
 ('wooden', 6),
 ('diabolical', 6),
 ('intense', 6),
 ('beloved', 6),
 ('favourite', 6),
 ('public', 6),
 ('intellectual', 6),
 ('suspicious', 6),
 ('left', 6),
 ('mortal', 6),
 ('immediate', 6),
 ('manifest', 5),
 ('proper', 5),
 ('hysterical', 5),
 ('ghostly', 5),
 ('jagged', 5),
 ('pleasant', 5),
 ('blank', 5),
 ('swift', 5),
 ('straight', 5),
 ('vast', 5),
 ('massive', 5),
 ('likely', 5),
 ('clean', 5),
 ('bushy', 5),
 ('immense', 5),
 ('True', 5),
 ('content', 5),
 ('sized', 5),
 ('startling', 5),
 ('instant', 5),
 ('castle', 5),
 ('bloody', 5),
 ('third', 5),
 ('brilliant', 5),
 ('golden', 5),
 ('cunning', 5),
 ('sensitive', 5),
 ('Same', 5),
 ('dizzy', 5),
 ('subtle', 5),
 ('closer', 5),
 ('earthly', 5),
 ('firm', 5),
 ('vital', 5),
 ('concerned', 5),
 ('unusual', 5),
 ('haggard', 5),
 ('startled', 5),
 ('restless', 5),
 ('loose', 5),
 ('infinite', 5),
 ('humble', 5),
 ('deeper', 5),
 ('younger', 5),
 ('pure', 5),
 ('apparent', 5),
 ('hush', 5),
 ('garlic', 5),
 ('pleased', 5),
 ('rude', 5),
 ('slow', 5),
 ('tender', 5),
 ('original', 5),
 ('individual', 5),
 ('leaden', 5),
 ('thicker', 5),
 ('post', 4),
 ('picturesque', 4),
 ('dirty', 4),
 ('fourth', 4),
 ('sorrowful', 4),
 ('bent', 4),
 ('brown', 4),
 ('snowy', 4),
 ('delicate', 4),
 ('weird', 4),
 ('keen', 4),
 ('courtly', 4),
 ('normal', 4),
 ('charming', 4),
 ('constant', 4),
 ('looking', 4),
 ('Strange', 4),
 ('ancient', 4),
 ('gay', 4),
 ('silver', 4),
 ('definite', 4),
 ('warlike', 4),
 ('smooth', 4),
 ('sheer', 4),
 ('wicked', 4),
 ('advanced', 4),
 ('rocky', 4),
 ('safer', 4),
 ('laden', 4),
 ('harsh', 4),
 ('vain', 4),
 ('odour', 4),
 ('lethal', 4),
 ('useless', 4),
 ('despairing', 4),
 ('idle', 4),
 ('nearest', 4),
 ('married', 4),
 ('haired', 4),
 ('hearted', 4),
 ('perfect', 4),
 ('Little', 4),
 ('determined', 4),
 ('sceptical', 4),
 ('_', 4),
 ('cruel', 4),
 ('zoöphagous', 4),
 ('anæmic', 4),
 ('sore', 4),
 ('greatest', 4),
 ('entire', 4),
 ('Russian', 4),
 ('steady', 4),
 ('missing', 4),
 ('ignorant', 4),
 ('additional', 4),
 ('agonising', 4),
 ('rosy', 4),
 ('strict', 4),
 ('deserted', 4),
 ('padded', 4),
 ('unexpected', 4),
 ('reasonable', 4),
 ('doubtless', 4),
 ('slight', 4),
 ('lethargic', 4),
 ('desolate', 4),
 ('feeble', 4),
 ('unable', 4),
 ('amazed', 4),
 ('prepared', 4),
 ('unclean', 4),
 ('hungry', 4),
 ('official', 4),
 ('brute', 4),
 ('highest', 4),
 ('hellish', 4),
 ('wily', 4),
 ('stable', 4),
 ('splendid', 3),
 ('Turkish', 3),
 ('thirsty', 3),
 ('harmless', 3),
 ('elderly', 3),
 ('polyglot', 3),
 ('Slovak', 3),
 ('rich', 3),
 ('lofty', 3),
 ('glorious', 3),
 ('purple', 3),
 ('pointed', 3),
 ('outer', 3),
 ('kindly', 3),
 ('eastern', 3),
 ('oppressive', 3),
 ('colder', 3),
 ('nearer', 3),
 ('momentary', 3),
 ('uncanny', 3),
 ('occasional', 3),
 ('remarkable', 3),
 ('marked', 3),
 ('locked', 3),
 ('suitable', 3),
 ('solid', 3),
 ('sleepless', 3),
 ('practical', 3),
 ('formal', 3),
 ('gruesome', 3),
 ('freer', 3),
 ('unlocked', 3),
 ('thorough', 3),
 ('nineteenth', 3),
 ('delightful', 3),
 ('repulsive', 3),
 ('lurid', 3),
 ('shadowy', 3),
 ('intact', 3),
 ('uncertain', 3),
 ('key', 3),
 ('square', 3),
 ('agonised', 3),
 ('powerful', 3),
 ('happier', 3),
 ('redder', 3),
 ('strained', 3),
 ('quickest', 3),
 ('inclined', 3),
 ('fancy', 3),
 ('ashamed', 3),
 ('worthy', 3),
 ('unselfish', 3),
 ('drunk', 3),
 ('fit', 3),
 ('wakeful', 3),
 ('nigh', 3),
 ('wet', 3),
 ('tempest', 3),
 ('inner', 3),
 ('foolish', 3),
 ('eyed', 3),
 ('fond', 3),
 ('paler', 3),
 ('languid', 3),
 ('respectful', 3),
 ('religious', 3),
 ('jealous', 3),
 ('horrid', 3),
 ('medical', 3),
 ('longer', 3),
 ('dull', 3),
 ('sullen', 3),
 ('alarmed', 3),
 ('thankful', 3),
 ('bewildered', 3),
 ('narcotic', 3),
 ('ashen', 3),
 ('prolonged', 3),
 ('probable', 3),
 ('nauseous', 3),
 ('known', 3),
 ('sovereign', 3),
 ('bold', 3),
 ('intent', 3),
 ('stupid', 3),
 ('frightful', 3),
 ('frantic', 3),
 ('frequent', 3),
 ('decent', 3),
 ('aware', 3),
 ('monstrous', 3),
 ('dreary', 3),
 ('harrowing', 3),
 ('gone', 3),
 ('blessed', 3),
 ('negative', 3),
 ('daily', 3),
 ('unholy', 3),
 ('smaller', 3),
 ('accustomed', 3),
 ('actual', 3),
 ('mistaken', 3),
 ('puzzled', 3),
 ('obedient', 3),
 ('instinct', 3),
 ('troubled', 3),
 ('electric', 3),
 ('huge', 3),
 ('future', 3),
 ('sound', 3),
 ('powerless', 3),
 ('gallant', 3),
 ('final', 3),
 ('higher', 3),
 ('Unclean', 3),
 ('plain', 3),
 ('flagged', 3),
 ('alert', 3),
 ('criminal', 3),
 ('derivative', 3),
 ('applicable', 3),
 ('defective', 3),
 ('LIMITED', 3),
 ('western', 2),
 ('extreme', 2),
 ('Carpathian', 2),
 ('continuous', 2),
 ('stony', 2),
 ('subject', 2),
 ('clumsy', 2),
 ('strangest', 2),
 ('stormy', 2),
 ('coloured', 2),
 ('reticent', 2),
 ('German', 2),
 ('ridiculous', 2),
 ('imperative', 2),
 ('idolatrous', 2),
 ('mixed', 2),
 ('sympathetic', 2),
 ('abreast', 2),
 ('level', 2),
 ('varied', 2),
 ('exciting', 2),
 ('slightest', 2),
 ('rolling', 2),
 ('sandy', 2),
 ('stranger', 2),
 ('prodigious', 2),
 ('minded', 2),
 ('flicker', 2),
 ('imperious', 2),
 ('moonlit', 2),
 ('bigger', 2),
 ('octagonal', 2),
 ('top', 2),
 ('absent', 2),
 ('political', 2),
 ('aged', 2),
 ('friendly', 2),
 ('myriad', 2),
 ('closed', 2),
 ('malignant', 2),
 ('prosaic', 2),
 ('veritable', 2),
 ('medium', 2),
 ('fascinating', 2),
 ('fell', 2),
 ('Hungarian', 2),
 ('unnatural', 2),
 ('sidelong', 2),
 ('clung', 2),
 ('tremble', 2),
 ('hateful', 2),
 ('Great', 2),
 ('merciful', 2),
 ('dreamy', 2),
 ('intolerable', 2),
 ('super', 2),
 ('languorous', 2),
 ('slender', 2),
 ('vile', 2),
 ('piteous', 2),
 ('winding', 2),
 ('muffled', 2),
 ('ruthless', 2),
 ('tiniest', 2),
 ('aërial', 2),
 ('extravagant', 2),
 ('naked', 2),
 ('British', 2),
 ('earthy', 2),
 ('stately', 2),
 ('swollen', 2),
 ('bloated', 2),
 ('overwhelmed', 2),
 ('handsome', 2),
 ('curly', 2),
 ('American', 2),
 ('momentous', 2),
 ('playful', 2),
 ('manly', 2),
 ('honest', 2),
 ('confused', 2),
 ('ungrateful', 2),
 ('valuable', 2),
 ('excitable', 2),
 ('happiest', 2),
 ('sweeter', 2),
 ('grand', 2),
 ('Sacred', 2),
 ('opposite', 2),
 ('raw', 2),
 ('exceptional', 2),
 ('pink', 2),
 ('easier', 2),
 ('giant', 2),
 ('Whitby', 2),
 ('mild', 2),
 ('downward', 2),
 ('lively', 2),
 ('incredible', 2),
 ('devouring', 2),
 ('damp', 2),
 ('flat', 2),
 ('chief', 2),
 ('impatient', 2),
 ('superstitious', 2),
 ('First', 2),
 ('calmer', 2),
 ('touching', 2),
 ('fright', 2),
 ('furious', 2),
 ('larger', 2),
 ('routine', 2),
 ('sublime', 2),
 ('shifty', 2),
 ('chloral', 2),
 ('bulky', 2),
 ('exhausted', 2),
 ('fat', 2),
 ('waistcoat', 2),
 ('functional', 2),
 ('malady', 2),
 ('stiff', 2),
 ('obscure', 2),
 ('truest', 2),
 ('appalling', 2),
 ('frenzied', 2),
 ('recuperative', 2),
 ('beneficial', 2),
 ('beneficent', 2),
 ('cerebral', 2),
 ('Quick', 2),
 ('pallid', 2),
 ('miss', 2),
 ('medicinal', 2),
 ('sceptic', 2),
 ('beset', 2),
 ('healthy', 2),
 ('hospitable', 2),
 ('unnecessary', 2),
 ('peaceful', 2),
 ('surgical', 2),
 ('farthest', 2),
 ('sternest', 2),
 ('unattended', 2),
 ('whiter', 2),
 ('professional', 2),
 ('mortem', 2),
 ('shocked', 2),
 ('lid', 2),
 ('eternal', 2),
 ('direct', 2),
 ('hostile', 2),
 ('youthful', 2),
 ('moral', 2),
 ('logical', 2),
 ('forceful', 2),
 ('mine', 2),
 ('comforting', 2),
 ('Quite', 2),
 ('following', 2),
 ('silly', 2),
 ('indicative', 2),
 ('typewritten', 2),
 ('dazzle', 2),
 ('mean', 2),
 ('barren', 2),
 ('overwrought', 2),
 ('corporeal', 2),
 ('comparative', 2),
 ('Indian', 2),
 ('aright', 2),
 ('northern', 2),
 ('fewer', 2),
 ('turnscrew', 2),
 ('dogged', 2),
 ('Most', 2),
 ('rose', 2),
 ('rational', 2),
 ('frank', 2),
 ('concentrated', 2),
 ('callous', 2),
 ('livid', 2),
 ('horrified', 2),
 ('carnal', 2),
 ('devilish', 2),
 ('nosferatu', 2),
 ('Brave', 2),
 ('hideous', 2),
 ('awkward', 2),
 ('chronological', 2),
 ('thoughtful', 2),
 ('ultimate', 2),
 ('central', 2),
 ('neutral', 2),
 ('emotional', 2),
 ('appealing', 2),
 ('contemptuous', 2),
 ('apt', 2),
 ('elemental', 2),
 ('positive', 2),
 ('live', 2),
 ('meaner', 2),
 ('limited', 2),
 ('idiotic', 2),
 ('conventional', 2),
 ('liable', 2),
 ('respectable', 2),
 ('amenable', 2),
 ('corrupt', 2),
 ('false', 2),
 ('indifferent', 2),
 ('unspeakable', 2),
 ('tenderly', 2),
 ('typical', 2),
 ('igh', 2),
 ('laconic', 2),
 ('worried', 2),
 ('weakest', 2),
 ('pitiful', 2),
 ('simplest', 2),
 ('forgetful', 2),
 ('holiest', 2),
 ('orderly', 2),
 ('devoted', 2),
 ('Hush', 2),
 ('greenish', 2),
 ('radiant', 2),
 ('loving', 2),
 ('latest', 2),
 ('sole', 2),
 ('doubtful', 2),
 ('predestinate', 2),
 ('commercial', 2),
 ('eneuch', 2),
 ('Many', 2),
 ('registered', 2),
 ('FULL', 2),
 ('readable', 2),
 ('widest', 2),
 ('exempt', 2),
 ('federal', 2),
 ('*', 1),
 ('contemporary', 1),
 ('1st', 1),
 ('national', 1),
 ('wildest', 1),
 ('distinct', 1),
 ('eleventh', 1),
 ('imaginative', 1),
 ('mamaliga', 1),
 ('unpunctual', 1),
 ('outside', 1),
 ('barbarian', 1),
 ('baggy', 1),
 ('enormous', 1),
 ('Oriental', 1),
 ('separate', 1),
 ('seventeenth', 1),
 ('modesty', 1),
 ('ungracious', 1),
 ('disagreeable', 1),
 ('gable', 1),
 ('bewildering', 1),
 ('fallen', 1),
 ('pine', 1),
 ('feverish', 1),
 ('serpentine', 1),
 ('prevalent', 1),
 ('greyness', 1),
 ('crazy', 1),
 ('thunderous', 1),
 ('universal', 1),
 ('mein', 1),
 ('rear', 1),
 ('louder', 1),
 ('manageable', 1),
 ('disturbed', 1),
 ('optical', 1),
 ('shaggy', 1),
 ('impalpable', 1),
 ('interminable', 1),
 ('customary', 1),
 ('blown', 1),
 ('shaven', 1),
 ('antique', 1),
 ('akin', 1),
 ('chill', 1),
 ('hasty', 1),
 ('graceful', 1),
 ('sealed', 1),
 ('discreet', 1),
 ('domed', 1),
 ('astonishing', 1),
 ('coarse', 1),
 ('squat', 1),
 ('rank', 1),
 ('protuberant', 1),
 ('confess', 1),
 ('costliest', 1),
 ('fabulous', 1),
 ('shaving', 1),
 ('Blue', 1),
 ('crowded', 1),
 ('flattering', 1),
 ('smallest', 1),
 ('bolder', 1),
 ('unchecked', 1),
 ('artificial', 1),
 ('triumphant', 1),
 ('undiscovered', 1),
 ('needful', 1),
 ('dilapidated', 1),
 ('sided', 1),
 ('cardinal', 1),
 ('gloomy', 1),
 ('mediæval', 1),
 ('straggling', 1),
 ('habitable', 1),
 ('Transylvanian', 1),
 ('attuned', 1),
 ('conceivable', 1),
 ('preternatural', 1),
 ('remiss', 1),
 ('wretched', 1),
 ('bauble', 1),
 ('annoying', 1),
 ('magnificent', 1),
 ('menial', 1),
 ('tangible', 1),
 ('European', 1),
 ('Ugric', 1),
 ('victorious', 1),
 ('unworthy', 1),
 ('dishonourable', 1),
 ('thinnest', 1),
 ('inaccessible', 1),
 ('nocturnal', 1),
 ('accursed', 1),
 ('amused', 1),
 ('impregnable', 1),
 ('bygone', 1),
 ('curtainless', 1),
 ('uncaring', 1),
 ('unchanged', 1),
 ('wavy', 1),
 ('musical', 1),
 ('Sweet', 1),
 ('deliberate', 1),
 ('scarlet', 1),
 ('Lower', 1),
 ('mirthless', 1),
 ('soulless', 1),
 ('aghast', 1),
 ('unquestionable', 1),
 ('unwound', 1),
 ('suavest', 1),
 ('fearless', 1),
 ('smoothest', 1),
 ('letters:--', 1),
 ('cheery', 1),
 ('surest', 1),
 ('villainy', 1),
 ('sturdy', 1),
 ('spade', 1),
 ('nebulous', 1),
 ('quicker', 1),
 ('metallic', 1),
 ('vaporous', 1),
 ('Greek', 1),
 ('circular', 1),
 ('sickly', 1),
 ('heavier', 1),
 ('genuine', 1),
 ('Close', 1),
 ('ponderous', 1),
 ('welcome', 1),
 ('fuller', 1),
 ('filthy', 1),
 ('nethermost', 1),
 ('cursed', 1),
 ('assistant', 1),
 ('stenographic', 1),
 ('hurried', 1),
 ('imperturbable', 1),
 ('tough', 1),
 ('psychological', 1),
 ('exquisite', 1),
 ('sloppy', 1),
 ('rarer', 1),
 ('wasn’t', 1),
 ('sanguine', 1),
 ('disturbing', 1),
 ('secure', 1),
 ('centripetal', 1),
 ('centrifugal', 1),
 ('paramount', 1),
 ('noblest', 1),
 ('lovelier', 1),
 ('roofed', 1),
 ('romantic', 1),
 ('nicest', 1),
 ('mournful', 1),
 ('cheap', 1),
 ('dictatorial', 1),
 ('nowt', 1),
 ('ireful', 1),
 ('acant', 1),
 ('slippy', 1),
 ('going:--', 1),
 ('poorish', 1),
 ('kirk', 1),
 ('aboon', 1),
 ('aftest', 1),
 ('bier', 1),
 ('Lively', 1),
 ('scorn', 1),
 ('pious', 1),
 ('stean', 1),
 ('stubble', 1),
 ('paved', 1),
 ('back', 1),
 ('wholesome', 1),
 ('Whole', 1),
 ('rudimentary', 1),
 ('sleek', 1),
 ('unprepared', 1),
 ('tame', 1),
 ('kitten', 1),
 ('undeveloped', 1),
 ('cumulative', 1),
 ('hopeless', 1),
 ('threatening', 1),
 ('vastness', 1),
 ('Dark', 1),
 ...]

In [18]:
# we make a dataframe from this list:

df = pd.DataFrame(adjs_tally.most_common(), columns=['adj', 'count'])
df[:100]

           adj  count
0         good    202
1        other    188
2          old    188
3         more    187
4          own    184
5        great    173
6         poor    171
7       little    162
8         much    151
9         dear    150
10        such    133
11        same    110
12        last    108
13       white    104
14        many    100
15    terrible     98
16        full     97
17        long     88
18         few     86
19     strange     85
20       first     78
21         new     74
22       ready     70
23       whole     66
24        open     66
25         red     65
26       sweet     65
27        dead     64
28        dark     62
29      strong     60
30        very     60
31        true     54
32       heavy     53
33       young     53
34       right     49
35        able     47
36       happy     47
37      asleep     47
38         big     44
39       quick     44
40       small     43
41        sure     43
42        best     42
43        cold     42
44      better     42
45        wild     41
46        free     41
47     certain     40
48     present     40
49      afraid     39
50        pale     38
51       quiet     37
52      silent     36
53       alone     36
54        high     35
55       close     35
56        glad     35
57       round     34
58       usual     33
59        thin     33
60         sad     33
61    possible     32
62       least     32
63         bad     32
64   beautiful     31
65         low     31
66       awful     31
67        hard     30
68       brave     30
69        next     29
70        deep     29
71        Good     29
72         mad     29
73     anxious     28
74   wonderful     27
75       empty     27
76  electronic     27
77        late     26
78      sudden     25
79    horrible     25
80       sharp     25
81   necessary     25
82        fair     25
83        safe     25
84        half     25
85        Dead     25
86       black     24
87        grim     24
88        only     24
89      bright     24
90       awake     24
91        wide     23
92   different     23
93       fresh     23
94       tired     23
95      common     23
96       noble     21
97       short     21
98    dreadful     21
99      bitter     21

In [19]:
# Get Nouns

nouns = []
for token in document:
    if token.pos_ == 'NOUN':
        nouns.append(token.text)

nouns_tally = Counter(nouns)

df = pd.DataFrame(nouns_tally.most_common(), columns=['noun', 'count'])
df[:100]

         noun  count
0        time    385
1       night    314
2         man    252
3        room    231
4         way    222
5         day    219
6        hand    202
7        door    199
8        face    196
9        eyes    188
10          _    178
11     things    172
12     friend    166
13       work    158
14       life    144
15      heart    140
16        men    138
17      place    133
18      house    133
19     window    116
20      sleep    116
21      blood    112
22     moment    106
23       head    104
24      hands    104
25        one    100
26    morning     97
27      thing     91
28        bed     90
29      death     88
30       mind     87
31     others     82
32       sort     79
33       fear     74
34      child     74
35       case     72
36      light     71
37    husband     71
38       side     67
39       word     66
40       rest     65
41       soul     65
42      world     63
43        box     63
44       dear     63
45       ship     62
46       part     61
47        end     61
48       days     61
49      water     59
50       lips     59
51      woman     57
52      diary     57
53       hour     56
54     horses     56
55      times     56
56      brain     55
57       body     55
58        sun     54
59        air     54
60       look     54
61      voice     52
62     fellow     51
63      words     50
64      earth     50
65      boxes     50
66    trouble     49
67    thought     49
68     mother     48
69     people     47
70       home     47
71    silence     47
72     morrow     46
73   strength     46
74       feet     46
75      power     46
76       kind     45
77      women     45
78     letter     45
79     wolves     45
80      cause     45
81     matter     45
82  knowledge     43
83        sea     43
84        key     43
85     throat     43
86       snow     42
87     sunset     42
88      teeth     42
89    patient     42
90    instant     41
91    friends     41
92       duty     40
93       fire     40
94       none     40
95        n’t     40
96     coffin     40
97     papers     39
98    minutes     39
99       wind     39

In [20]:
# Get Verbs

verbs = [token.text for token in document if token.pos_ == 'VERB']

verbs_tally = Counter(verbs)

df = pd.DataFrame(verbs_tally.most_common(), columns=['verb', 'count'])
df[:100]

          verb  count
0         said    461
1         know    396
2          see    377
3         have    342
4         came    301
5         went    298
6         come    296
7           do    285
8          had    277
9           go    271
10      seemed    242
11        took    223
12         saw    216
13       think    216
14        made    196
15      looked    186
16         was    183
17        tell    175
18         get    167
19        make    164
20         got    156
21          is    153
22       found    153
23        told    142
24         say    140
25       asked    139
26        take    136
27        knew    130
28        done    128
29        find    114
30         let    113
31        want    110
32       began    109
33         put    106
34     thought    105
35        hear    101
36      coming    100
37        look     97
38        seen     95
39        keep     94
40       heard     91
41     looking     89
42        felt     87
43        left     85
44      turned     84
45       stood     80
46      opened     80
47          be     80
48        read     79
49        give     78
50        help     78
51        feel     77
52       sleep     74
53        held     73
54       seems     72
55         are     72
56         lay     70
57        gone     69
58         sat     69
59         ask     68
60        gave     67
61         set     65
62        seem     65
63         has     65
64     believe     65
65       going     64
66       spoke     64
67         try     64
68       speak     62
69       tried     62
70       write     61
71        fear     61
72         did     60
73        fell     57
74        kept     55
75  understand     55
76      passed     55
77       leave     55
78     suppose     53
79     said:--     52
80         ran     50
81    answered     50
82        love     48
83       taken     47
84        grew     47
85        used     47
86          ’s     47
87        were     46
88        lost     45
89         die     45
90      called     44
91        says     44
92       given     43
93     stopped     43
94      wanted     43
95        like     43
96       moved     43
97        wish     43
98        wait     42
99        laid     42